### ISSUE TITLE
Clarify what dynamicRegistration is for in the docs.

### ISSUE THREAD

**Issue by thekaganugur** [mrshmllow/document-color.nvim#5]
Hi,
I just saw that `dynamicRegistration` was added to the recommended setup.
```
capabilities.textDocument.colorProvider = {
  dynamicRegistration = true
}
```
But couldn't find why this is needed (not sure if it's needed though). Since I'm already using the plunging without this snippet.

Thanks.

**Comment by mrshmllow** [comment]
it's in the docs https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentClientCapabilities. simply passing true will break servers (like rust https://github.com/rust-lang/rust-analyzer/issues/13068)
